name       : deepin-menu
version    : 3.3.10
release    : 1
source     :
    - git|https://github.com/linuxdeepin/deepin-menu.git : 3.3.10
license    : GPL-3.0-only
component  : desktop.deepin.core
summary    : Unified menu service for Deepin Desktop Environment.
description: |
    Deepin Menu is the unified menu service for Deepin Desktop Environment.
builddeps  :
    - pkgconfig(dtkwidget)
    - qt5-tools-devel
setup      : |
    %qmake PREFIX=%PREFIX% LIB_INSTALL_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -dm 755 "${installdir}/etc/xdg/autostart/"
    install -m 644 *.desktop "${installdir}/etc/xdg/autostart/"
