name       : deepin-terminal
version    : 3.0.1
release    : 1
source     :
    - git|https://github.com/linuxdeepin/deepin-terminal.git : 3.0.1
license    : GPL-3.0-only
component  : desktop.deepin
summary    : The default terminal emulation application for Deepin.
description: |
    The default terminal emulation application for Deepin.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(vte-2.91)
    - vala
rundeps    :
    - expect
setup      : |
    %patch -p1 < $pkgfiles/remove-vendor.patch
    %patch -p1 < $pkgfiles/0001-CMakeLists-Remove-specific-Glib-version.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
